trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  projectPath1: 'maatwerkgiethoorn.blazor.extendedsessionstate/maatwerkgiethoorn.blazor.extendedsessionstate.csproj'
  projectPath2: 'maatwerkgiethoorn.blazor.extendedsessionstate.server/maatwerkgiethoorn.blazor.extendedsessionstate.server.csproj'

steps:
# Restore, Build, and Pack in a single DotNetCoreCLI task
- task: DotNetCoreCLI@2
  displayName: "Restore, Build, and Pack for mwg.blazor.ExtendedSessionState"
  inputs:
    command: 'pack'
    projects: '$(projectPath1)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'BUILD_BUILDNUMBER'

# Add the second project
- task: DotNetCoreCLI@2
  displayName: "Restore, Build, and Pack for maatwerkgiethoorn.blazor.extendedsessionstate.server"
  inputs:
    command: 'pack'
    projects: '$(projectPath2)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'BUILD_BUILDNUMBER'

# Push the package to the feed
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '9331453b-bfee-4673-a7af-6a642e1b7e14'
    allowPackageConflicts: true

# Push the package to the public NuGet repository
- task: NuGetCommand@2
  displayName: 'NuGet push to NuGet.org'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet push'
