name: Publish NuGet Package

on:
  push:
    branches:
      - master
    tags:
      - 'v*'  # Trigger the workflow when a tag starting with "v" is pushed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore maatwerkgiethoorn.blazor.extendedsessionstate.sln

      - name: Build the projects
        run: dotnet build maatwerkgiethoorn.blazor.extendedsessionstate.sln --configuration Release --no-restore
      # Find and pack all projects under Src\ folder
      - name: Pack all projects in Src
        run: |
          for csproj in $(find Src -name "*.csproj"); do
            dotnet pack $csproj --configuration Release --no-build -p:PackageVersion=${{ github.ref_name[1:] }}
          done

      # Push the packages to NuGet
      - name: Push packages to NuGet
        run: dotnet nuget push Src/**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
