name: Build and Publish NuGet Packages

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET SDK (version 8.0.x)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Step 3: Restore dependencies for the solution
      - name: Restore dependencies
        run: dotnet restore maatwerkgiethoorn.blazor.extendedsessionstate.sln

      # Step 4: Build the solution
      - name: Build the solution
        run: dotnet build maatwerkgiethoorn.blazor.extendedsessionstate.sln --configuration Release --no-restore

      # Step 5: Pack all projects in the Src folder, using the tag version
      - name: Pack Server
        run: dotnet pack Src/maatwerkgiethoorn.blazor.extendedsessionstate.server/maatwerkgiethoorn.blazor.extendedsessionstate.server.csproj  --configuration Release --no-build -p:PackageVersion=1.3.0
      - name: Pack WebAssembly        
        run: dotnet pack Src/maatwerkgiethoorn.blazor.extendedsessionstate/maatwerkgiethoorn.blazor.extendedsessionstate.webassembly.csproj  --configuration Release --no-build -p:PackageVersion=1.3.0

      # Step 6: Push the packages to NuGet
      #- name: Push packages to NuGet
      #  run: dotnet nuget push Src/**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      #  env:
      #    NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  # NuGet API key stored in GitHub Secrets
